# Single Match Analysis - Final Match

## 0. Setup - Imports and Configuration

In [18]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import config
from src.analysis.game_utils import game_summary
from src.analysis.prediction_utils import normalize_predictions, print_top_predictions, get_top_indices, create_top_sequences, visualize_top_sequences
from src.data.data_loader import load_socceraction_match
from src.ml.models.model_factory import load_model
from src.ml.preprocessing.sequence_preprocessor import SequencePreprocessor, PreprocessingMode
from src.ml.preprocessing.xthreat import get_default_xt_model

In [19]:
# Configure pandas display options
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

## 1. Load ratings

In [20]:
transformer_ratings = pd.read_csv("generated/ratings/player_contributions_match_3943043_transformer.csv")
print(transformer_ratings.columns)
transformer_ratings.head()

Index(['total_value', 'num_sequences', 'avg_value', 'max_value', 'player_id', 'player_name', 'team_name'], dtype='object')

   total_value  num_sequences  avg_value  max_value  player_id                  player_name team_name
0     1.720473            102   0.016867   0.179595      68574    Nicholas Williams Arthuer     Spain
1     1.222608             71   0.017220   0.919108       3943                  Declan Rice   England
2     0.817241             75   0.010897   0.187941     316046  Lamine Yamal Nasraoui Ebana     Spain
3     0.798686            125   0.006389   0.185811       6655             Fabián Ruiz Peña     Spain
4     0.682922             77   0.008869   0.180763       3205                  Kyle Walker   England

In [21]:
attention_lstm_ratings = pd.read_csv("generated/ratings/player_contributions_match_3943043_attention_lstm.csv")
attention_lstm_ratings.head()

   total_value  num_sequences  avg_value  max_value  player_id                player_name team_name
0     1.242785            102   0.012184   0.118721      68574  Nicholas Williams Arthuer     Spain
1     0.962968            125   0.007704   0.055847       6655           Fabián Ruiz Peña     Spain
2     0.776907            126   0.006166   0.050386       5721      Daniel Carvajal Ramos     Spain
3     0.709577             70   0.010137   0.035139      16532       Daniel Olmo Carvajal     Spain
4     0.660164            152   0.004343   0.058445       4353            Aymeric Laporte     Spain

In [22]:
sofascore_rating = pd.read_csv("generated/ratings/sofacore.csv")
sofascore_rating

                        player_name team_name    Pozycja  sofascore_rating
0         Nicholas Williams Arthuer     Spain   Pomocnik               7.9
1                   Jude Bellingham   England   Pomocnik               7.7
2       Lamine Yamal Nasraoui Ebana     Spain   Pomocnik               7.5
3            Mikel Oyarzabal Ugarte     Spain  Napastnik               7.5
4                  Fabián Ruiz Peña     Spain   Pomocnik               7.4
5                   Jordan Pickford   England   Bramkarz               7.4
6                       Cole Palmer   England  Napastnik               7.3
7             Marc Cucurella Saseta     Spain    Obrońca               7.1
8                   Aymeric Laporte     Spain    Obrońca               7.0
9           Martín Zubimendi Ibáñez     Spain   Pomocnik               7.0
10             Daniel Olmo Carvajal     Spain   Pomocnik               6.9
11     Robin Aime Robert Le Normand     Spain    Obrońca               6.9
12                      Bukayo Saka   England   Pomocnik               6.8
13                      Declan Rice   England   Pomocnik               6.8
14                      Kyle Walker   England    Obrońca               6.8
15                        Luke Shaw   England    Obrońca               6.8
16                       Phil Foden   England   Pomocnik               6.8
17       Rodrigo Hernández Cascante     Spain   Pomocnik               6.8
18            Daniel Carvajal Ramos     Spain    Obrońca               6.7
19                      John Stones   England    Obrońca               6.7
20                       Marc Guehi   England    Obrońca               6.7
21  José Ignacio Fernández Iglesias     Spain    Obrońca               6.6
22                       Harry Kane   England  Napastnik               6.5
23                    Kobbie Mainoo   England   Pomocnik               6.5
24              Unai Simón Mendibil     Spain   Bramkarz               6.5
25                    Ollie Watkins   England  Napastnik               6.4
26       Álvaro Borja Morata Martín     Spain  Napastnik               6.3

## 2. Analysis

In [23]:
# Merge all ratings
attention_lstm_prep = attention_lstm_ratings[['player_name', 'team_name', 'total_value']].rename(columns={
    'total_value': 'attention_lstm_total_value',
})

transformer_prep = transformer_ratings[['player_name', 'team_name', 'total_value', 'num_sequences']].rename(columns={
    'total_value': 'transformer_total_value',
})

sofascore_prep = sofascore_rating[['player_name', 'team_name', 'sofascore_rating']]

# Merge all dataframes
all_ratings = attention_lstm_prep.merge(
    transformer_prep,
    on=['player_name', 'team_name'],
    how='outer'
).merge(
    sofascore_prep,
    on=['player_name', 'team_name'],
    how='outer'
)

# Convert num_sequences columns to int
all_ratings['num_sequences'] = all_ratings['num_sequences'].astype(int)

# Sort by attention_lstm_total_value
all_ratings = all_ratings.sort_values('attention_lstm_total_value', ascending=False)

all_ratings

                        player_name team_name  attention_lstm_total_value  transformer_total_value  num_sequences  sofascore_rating
20        Nicholas Williams Arthuer     Spain                    1.242785                 1.720473            102               7.9
6                  Fabián Ruiz Peña     Spain                    0.962968                 0.798686            125               7.4
3             Daniel Carvajal Ramos     Spain                    0.776907                 0.665989            126               6.7
4              Daniel Olmo Carvajal     Spain                    0.709577                 0.506555             70               6.9
0                   Aymeric Laporte     Spain                    0.660164                 0.568710            152               7.0
23     Robin Aime Robert Le Normand     Spain                    0.658067                 0.431317            153               6.9
14      Lamine Yamal Nasraoui Ebana     Spain                    0.571512                 0.817241             75               7.5
5                       Declan Rice   England                    0.531927                 1.222608             71               6.8
11                  Jude Bellingham   England                    0.528454                 0.468874             66               7.7
1                       Bukayo Saka   England                    0.410017                 0.448848             56               6.8
16            Marc Cucurella Saseta     Spain                    0.399601                 0.306261             72               7.1
13                      Kyle Walker   England                    0.393855                 0.682922             77               6.8
2                       Cole Palmer   England                    0.325124                 0.113589             17               7.3
15                        Luke Shaw   England                    0.292242                 0.161688             40               6.8
9                   Jordan Pickford   England                    0.281185                 0.417774             64               7.4
26       Álvaro Borja Morata Martín     Spain                    0.271885                 0.312120             36               6.3
24       Rodrigo Hernández Cascante     Spain                    0.248214                 0.164175             52               6.8
18          Martín Zubimendi Ibáñez     Spain                    0.246769                 0.150650             49               7.0
25              Unai Simón Mendibil     Spain                    0.236182                 0.126814             60               6.5
8                       John Stones   England                    0.210185                 0.165650             58               6.7
22                       Phil Foden   England                    0.188746                 0.278242             35               6.8
12                    Kobbie Mainoo   England                    0.184102                 0.187179             37               6.5
17                       Marc Guehi   England                    0.175313                 0.133231             39               6.7
7                        Harry Kane   England                    0.129419                 0.122461             16               6.5
19           Mikel Oyarzabal Ugarte     Spain                    0.123525                 0.164661              8               7.5
21                    Ollie Watkins   England                    0.093127                 0.111956              5               6.4
10  José Ignacio Fernández Iglesias     Spain                    0.013059                 0.016141              6               6.6

### Save to csv

In [24]:
all_ratings.to_csv("generated/ratings/all_ratings.csv")

In [25]:
all_ratings.columns

Index(['player_name', 'team_name', 'attention_lstm_total_value', 'transformer_total_value', 'num_sequences', 'sofascore_rating'], dtype='object')